version: "3.0"
services:
  undb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: undb
    ports:
      - 3721:3721
    environment:
      - UNDB_DB_TURSO_URL=${UNDB_DB_TURSO_URL}
      - UNDB_DB_TURSO_AUTH_TOKEN=${UNDB_DB_TURSO_AUTH_TOKEN}
